### ISSUE TITLE
Bug , profile page emial toggle do not work

### ISSUE THREAD

**Issue by lucasverra** [lucasverra/kind-robin#21]
![image](https://user-images.githubusercontent.com/11323803/78984906-b93dd680-7b27-11ea-80ac-94db4fcfdd7c.png)

this toggles does not work anymore, it cannot be passed to yes

**Comment by blackjmxx** [comment]
Besoin de contexte pour reproduire

**Comment by lucasverra** [comment]
latest firefox sur win10 , sur kind robin

nouvel et ancien user

**Comment by blackjmxx** [comment]
Je ne peux pas reçu produire ce cas là. Ça marche sur mon Firefox.

**Comment by lucasverra** [comment]
Ios dafari same issue 

![9CCC9DFE-F15C-483A-9F4E-B811FBE39B68](https://user-images.githubusercontent.com/11323803/79047523-5b88b780-7c17-11ea-9c47-5dbb49bf92ff.png)

**Comment by lucasverra** [comment]
![0D5B928E-1050-49E0-B152-F982A1BCB22D](https://user-images.githubusercontent.com/11323803/79047942-013d2600-7c1a-11ea-872a-9362549cd98a.jpeg)
Log

**Comment by lucasverra** [comment]
issue on adblockers
